os: linux
dist: focal

language: python
cache: pip
python:
  - "3.8"

jobs:
  include:
    - name: "Lint"
      install:
        - pip install black==20.8b1 isort==4.3.21
      script:
        - black donate_anything config --check && isort -c -rc -lai 2 -df

    - name: "Django Test"
      addons:
        postgresql: '12'
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        - PGVER=12
        - PGPORT=5433
        - USE_DOCKER="no"
        - DATABASE_URL="postgres:///donate_anything"
        - CELERY_BROKER_URL="redis://localhost:6379/0"
      services:
        - redis
      install:
        - sudo apt-get install -y swig
        - pip install -r requirements/local.txt
      before_script:
        - sudo mkdir /var/run/celery
        - sudo mkdir /var/log/celery
        - sudo chown travis /var/log/celery
        - sudo chown travis /var/run/celery
        - celery multi start worker beat -A config.celery_app --pool=solo
      script:
        - "pytest"

  allow_failures:
    - name: "Lint"
      if: branch = master
