version: '3'

services:
  django: # &django
    build:
      context: .
      dockerfile: ./compose/production/self/django/Dockerfile
    image: da_production_blue_django
    networks:
      - da-front-network
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    deploy:
      labels:
        - "traefik.http.routers.colors-blue.priority=100"
        - "traefik.http.routers.colors-blue.rule=Path(`/`)"
        - "traefik.http.services.colors-blue.loadbalancer.server.port=5000"

#  celeryworker:
#    <<: *django
#    image: da_production_celeryworker
#    command: /start-celeryworker
#
#  celerybeat:
#    <<: *django
#    image: da_production_celerybeat
#    command: /start-celerybeat
#
#  flower:
#    <<: *django
#    image: da_production_flower
#    command: /start-flower

networks:
  da-front-network:
    external: true
