# Generated by Django 3.0.8 on 2020-07-24 18:26

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("charity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("submitted", models.DateField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Entity"),
                ),
                ("link", models.URLField(verbose_name="Link to website (or platform)")),
                (
                    "description",
                    models.TextField(
                        max_length=1000, verbose_name="Organization description"
                    ),
                ),
                (
                    "how_to_donate",
                    models.TextField(max_length=300, verbose_name="How to Donate"),
                ),
                (
                    "specific_destination",
                    models.CharField(
                        max_length=50, verbose_name="Specific destination"
                    ),
                ),
                ("closed", models.BooleanField(default=False)),
                (
                    "years_of_service",
                    models.PositiveSmallIntegerField(verbose_name="Years of service"),
                ),
                (
                    "reason",
                    models.CharField(
                        max_length=200, verbose_name="Reason for donations"
                    ),
                ),
                (
                    "type_of_business",
                    models.CharField(
                        max_length=120, verbose_name="All your business model(s)."
                    ),
                ),
                (
                    "applier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="OrganizationApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("submitted", models.DateField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Entity"),
                ),
                ("link", models.URLField(verbose_name="Link to website (or platform)")),
                (
                    "description",
                    models.TextField(
                        max_length=1000, verbose_name="Organization description"
                    ),
                ),
                (
                    "how_to_donate",
                    models.TextField(max_length=300, verbose_name="How to Donate"),
                ),
                (
                    "specific_destination",
                    models.CharField(
                        max_length=50, verbose_name="Specific destination"
                    ),
                ),
                ("closed", models.BooleanField(default=False)),
                (
                    "chapter_filing",
                    models.TextField(
                        max_length=2000, verbose_name="Public Legal Documentation"
                    ),
                ),
                ("extra", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    "applier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProposedOrganizationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(), size=10000
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charity.OrganizationApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProposedBusinessItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(), size=10000
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charity.BusinessApplication",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="AppliedOrganizationEdit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("edit", models.TextField(max_length=5000)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "proposed_entity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="charity.OrganizationApplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="AppliedBusinessEdit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("edit", models.TextField(max_length=5000)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "proposed_entity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="charity.BusinessApplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
