# Generated by Django 3.1 on 2020-11-14 15:50

from django.db import migrations, models

import donate_anything.charity.models.charity


class Migration(migrations.Migration):

    dependencies = [
        ("charity", "0004_auto_20200822_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="charity",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=donate_anything.charity.models.charity.unique_image,
                verbose_name="Logo",
            ),
        ),
    ]
