# Generated by Django 3.1 on 2020-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_banreason_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedEmail",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
