# Generated by Django 3.1 on 2020-08-15 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity", "0003_proposededit"),
        ("users", "0003_blacklistedemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedAccount",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                ("reason", models.TextField(max_length=300)),
                ("accepted", models.BooleanField(default=False)),
                ("submitted_on", models.DateField(auto_now_add=True)),
                ("verified_on", models.DateField(blank=True, null=True)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charity.charity",
                    ),
                ),
            ],
        ),
    ]
