# Generated by Django 3.0.8 on 2020-07-28 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "General Message"),
                            (1, "Organization Application"),
                            (2, "Business Application"),
                            (3, "Entity Suggested Edit"),
                            (4, "Adding/Removing Items"),
                        ]
                    ),
                ),
                ("views", models.BigIntegerField(default=0)),
                ("accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserVote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "direction",
                    models.BooleanField(
                        choices=[(True, "Upvote"), (False, "Downvote")]
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.Thread"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("message", models.TextField(max_length=5000)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.Thread"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
