from django.db.models.signals import post_save
from django.urls import reverse

from donate_anything.forum.models import Message, Thread
from donate_anything.item.models import ProposedItem


current_domain = "https://donate-anything.org"


def create_thread_proposed_item(instance: ProposedItem, created, **kwargs):
    if created:
        thread = Thread.objects.create(
            title=f"New Proposed Items for {instance.entity.name}", type=4
        )
        Message.objects.create(
            user=instance.user,
            thread=thread,
            message="You can view the proposed items here: "
            f"{current_domain}{reverse('item:list-proposed-template', kwargs={'proposed_item_pk': instance.id})}."
            "\n*Generated by the system.*",
        )


post_save.connect(create_thread_proposed_item, sender=ProposedItem)
