from django.conf import settings
from django.db.models.signals import post_save
from django.urls import reverse

from donate_anything.charity.models import (
    BusinessApplication,
    OrganizationApplication,
    ProposedEdit,
)
from donate_anything.forum.models import Message, Thread


if settings.DEBUG:
    current_domain = "http://localhost:8000"
else:
    current_domain = "https://donate-anything.org"


def create_thread_on_apply(sender, instance, created, **kwargs):
    if created:
        thread = Thread.objects.create(
            title=f"New Application: {instance.name}",
            type=1 if sender == OrganizationApplication else 2,
        )
        url = current_domain
        if sender == BusinessApplication:
            url += reverse("charity:applied-business", kwargs={"pk": instance.id})
        else:
            url += reverse("charity:applied-organization", kwargs={"pk": instance.id})
        Message.objects.create(
            user=instance.applier,
            thread=thread,
            message=f"You can view the application here: {url}."
            "\n*Generated by the system.*",
        )


post_save.connect(create_thread_on_apply, BusinessApplication)
post_save.connect(create_thread_on_apply, OrganizationApplication)


def create_thread_on_suggest(instance, created, **kwargs):
    """Creates a new thread in the community forum when a suggestion
    for an ACTIVE organization/entity is created.
    """
    if created:
        thread = Thread.objects.create(
            title=f"New Suggestion for {instance.entity.name}", type=3
        )
        Message.objects.create(
            user=instance.user,
            thread=thread,
            message="You can view the suggestion here: "
            f"{current_domain}{reverse('forum:thread', kwargs={'thread': thread.id})}."
            "\n*Generated by the system.*",
        )


post_save.connect(create_thread_on_suggest, ProposedEdit)
