# Generated by Django 3.0.8 on 2020-07-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("is_appropriate", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WantedItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charity.Charity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="item.Item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Financial"),
                            (1, "Clothing"),
                            (2, "Kitchenware"),
                            (3, "Books and Media"),
                            (4, "Toys and Games"),
                            (5, "Art"),
                            (6, "Hygiene"),
                            (7, "Sports"),
                            (8, "Furniture"),
                            (9, "Electronics"),
                            (10, "Internal Health"),
                            (11, "School Supplies"),
                            (12, "Linen"),
                            (13, "Recyclables"),
                            (14, "Compost"),
                            (15, "Food and Liquids"),
                            (16, "Miscellaneous"),
                        ]
                    ),
                ),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charity.Charity",
                    ),
                ),
            ],
        ),
    ]
