# Build and push the nginx image
#
# Since my ECR free tier was at stake, and since
# nginx takes a relatively short amount of time to
# build anyways, I decided to move the build and
# push to separate file since nginx configuration
# doesn't change too often.

name: Build and Push NGINX Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Trigger this workflow on master push
      - 'compose/production/ecs/nginx/**'
      - '.github/workflows/nginx.yml'

jobs:
  build-nginx:
    name: Build NGINX Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build nginx
    # -------------------------------------------------------
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: donateanything/nginx-reverse-proxy
        tags: ${{ github.sha }},latest
        dockerfile: compose/production/ecs/nginx/Dockerfile
